name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs: 
  Third_Lab_Build:
    name: Build Third Lab
    runs-on: ubuntu-latest
    env:
      SOURCE_DIR: Third/Third_Laboratory_Work/

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: GitGuardian scan
      uses: GitGuardian/gg-shield-action@master
      env:
        GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
        GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
        GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

    - name: Grant execute permission for gradlew
      run: |
        cd $SOURCE_DIR
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd $SOURCE_DIR
        ./gradlew build
